# Numpy

Pada topik ini kita akan membahas sebuah library yang bisa dimanfaatkan untuk mengolah data dalam bentuk array. Library tersebut bernama ``Numpy``. Dokumentasi lengkap perihal numpy dapat dilihat pada https://numpy.org/.

Sebelum bisa menggunakan module ``numpy``, pastikan module ini sudah dipasang di lingkungan Python yang digunakan. Perintah instalasinya sebagai berikut:

<b>Instalasi via pip</b> <br>
``pip3 install numpy``

<b>Instalasi via conda</b> (secara default sudah tersedia ketika instalasi Anaconda atau Miniconda) <br>
``conda install numpy``

Setelah melakukan instalasi, mari kita masuk ke pembahasan module ``numpy`` ini.

In [6]:
!pip3 show numpy

Name: numpy
Version: 1.20.3
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: /usr/local/anaconda3/lib/python3.8/site-packages
Requires: 
Required-by: tifffile, tables, statsmodels, seaborn, scipy, scikit-learn, scikit-image, PyWavelets, pyerfa, patsy, pandas, numexpr, numba, mkl-random, mkl-fft, matplotlib, imageio, h5py, Bottleneck, bokeh, bkcharts, astropy


In [9]:
import numpy as np

print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__sp

## Numpy Array vs. Python List

Numpy memiliki struktur data yang mirip seperti List, yaitu numpy array. Numpy array lebih efisien dalam penggunaan resource dan lebih cepat dalam pengaksesannya. Berikut adalah contoh penggunaan numpy array:

In [10]:
import numpy as np

array = np.array([1, 'a', 2, 'b'])
print(array)
print(array[1])
print(array[1:3])
print(array[:3])
print(array[1:])
print(array[-1])
print(array[-1:-3:-1])

['1' 'a' '2' 'b']
a
['a' '2']
['1' 'a' '2']
['a' '2' 'b']
b
['b' '2']


Tampilan array-nya sama dengan list yang ada pada python bahkan operasi slicingnya sama dengan list yang ada di Python. Jadi tidak perlu khawatir untuk menggunakan array dari numpy ini. Kita juga bisa mengkonversi list python menjadi numpy array dengan cara type casting. Berikut cara penggunaannya:

In [11]:
import numpy as np

list_python = [1, 'a', 2, 'b', 'adam']

array_numpy = np.array(list_python)
print(type(array_numpy))

<class 'numpy.ndarray'>


Sama seperti list, numpy array juga bisa direpresentasikan menjadi array dua dimensi. Berikut adalah contoh penggunaanya:

In [12]:
import numpy as np

list_2d = [[10, 20, 30],[40, 50, 60], [70, 80, 90]]
print(list_2d)

print()

array_2d = np.array(list_2d)
print(array_2d)

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]

[[10 20 30]
 [40 50 60]
 [70 80 90]]


Kita bisa melihat bahwa numpy array lebih representatif untuk kita gunakan.

### Generate Array di Numpy

Numpy memiliki konsep generator yang mirip seperti list di Python. Apabila di list kita menggunakan ``range()`` yang disimpan dalam sebuah struktur perulangan, maka kita bisa menggunakan method ``arange()`` di numpy. Secara konsep, fungsi ini sebagai pengganti generator ``range()``. Berikut contoh penggunaannya:

In [13]:
import numpy as np

# List di Python
list_bil = []
for i in range(0,11):
    list_bil.append(i)

print(list_bil)

# numpy array
array = np.arange(0,11)
print(array)

array = np.arange(0,11,2)
print(array)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10]


Selain untuk meng-generate array seperti contoh tadi, numpy memiliki kemampuan untuk membuat array berisi bilangan 0 (berguna untuk operasi matriks). Fungsi yang digunakan adalah ``zeros()``. Berikut cara penggunaannya:

In [14]:
import numpy as np

array_nol = np.zeros(10)
print(array_nol)

print()

array_nol_2d = np.zeros((10, 10))
print(array_nol_2d)

print()

array_nol_2d = np.zeros((10, 10), dtype= int)
print(array_nol_2d)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


Selain ``zeros()`` numpy juga memiliki method ``ones()`` yang fungsinya mirip seperti ``zeros()`` akan tetapi nilai ynag di-generate adalah 1.

In [15]:
import numpy as np

array_satu = np.ones(10)
print(array_satu)

print()

array_satu_2d = np.ones((5, 10))
print(array_satu_2d)

print()

array_satu_2d = np.ones((5, 10),dtype=int)
print(array_satu_2d)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


### Generate Spaced Number di Numpy

Kita bisa menggunakan fungsi ``linspace()`` untuk generate spaced number pada interval yang ditentukan. Berikut contoh penggunaannya:

In [16]:
import numpy as np

matriks = np.linspace(0,10)
print(matriks)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [17]:
import numpy as np

matriks = np.linspace(0, 10, 100)
print(matriks)

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

### Matriks Indentitas

Numpy memiliki fungsi ``eye()`` yang memungkinkan programmer untuk membuat matriks identitas dengan jumlah tertentu. Pengertian dan kegunaan matriks identitas dapat dipelajari singkat di https://id.wikipedia.org/wiki/Matriks_identitas. Berikut contoh penggunaannya:

In [18]:
import numpy as np

matriks_identitas = np.eye(5)
print(matriks_identitas)

print()

matriks_identitas = np.eye(3)
print(matriks_identitas)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Generate Array Random

Numpy memiliki fungsi yang memungkinkan programmer membuat array berisi data random. Konsep random di numpy memiliki mekanisme yang mirip dengan Python. Berikut contoh penggunaannya:

In [19]:
import numpy as np

rand_array = np.random.rand(5)
print(rand_array)

print()

rand_matriks = np.random.rand(5,5)
print(rand_matriks)

[9.52680657e-01 6.94873329e-01 6.55970162e-04 8.37550112e-01
 9.22603264e-01]

[[0.06778392 0.42849386 0.8970842  0.79079473 0.85264962]
 [0.48593313 0.80013812 0.87072799 0.03459777 0.35590764]
 [0.66236895 0.89988787 0.52116749 0.01732324 0.20955398]
 [0.30782611 0.99407114 0.17039466 0.44276317 0.3257748 ]
 [0.2632885  0.25347162 0.34835578 0.56835171 0.39986205]]


Selain fungsi tersebut, numpy bisa menghasilkan random array yang berisi angka random untuk distribusi normal standar. Berikut contoh penggunaannya:

In [20]:
import numpy as np

rand_normal_array = np.random.randn(5)
print(rand_normal_array)

print()

rand_normal_matriks = np.random.randn(4,4)
print(rand_normal_matriks)

[-1.31452967  0.54355762  0.79667224 -0.72417649  0.29087399]

[[ 1.30755511  0.7221786   0.81215944  0.50188437]
 [-1.30168892  0.55670429  0.064297    2.07919693]
 [ 0.39509241 -0.03141488  1.25798941  0.63463889]
 [-0.69688348 -0.25724291 -0.41419047  1.20017169]]


Fungsi random dari numpy yang akan dibahas terakhir adalah ``randint()``. Fungsi ini memiliki kemiripan dengan fungsi ``randint()`` di python. Berikut contoh penggunaannya:

In [21]:
import numpy as np

nilai_random = np.random.randint(1,10)
print(nilai_random)

rand_int_array = np.random.randint(1,10,10)
print(rand_int_array)

6
[6 2 1 6 7 2 3 6 1 5]


### Fungsi reshape()

Fungsi ``reshape()`` memungkinkan kita untuk membentuk suatu array dengan dimensi menjadi array dengan dimensi lain. Berikut contoh penggunaannya:

In [22]:
import numpy as np

array = np.random.randint(1,10,25)
print(array)

print()

matriks_55 = array.reshape(5,5)
print(matriks_55)

[8 6 4 5 6 4 3 1 6 8 8 5 3 2 6 5 3 4 1 5 4 2 2 8 9]

[[8 6 4 5 6]
 [4 3 1 6 8]
 [8 5 3 2 6]
 [5 3 4 1 5]
 [4 2 2 8 9]]


><b>Catatan:</b> Jumlah elemen pada array yang mau dibentuk ulang harus sama dengan jumlah elemen pada dimensi array yang baru.

## Operasi pada Array

Numpy bisa kita gunakan untuk mempermudah perhitungan atau operasi-operasi pada array atau matriks. Berikut adalah bahasan tentang operasi pada array dan matriks yang bisa didukung (sering digunakan) oleh numpy.

### Pertambahan Array

Layaknya di ilmu Matematika, array bisa ditambahkan dengan array lainnya. Berikut contoh operasi pertambahan pada array menggunakan numpy:

In [23]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.ones(3, dtype = int)

array_hasil = array1 + array2
array_tambah = array1 + 10

print(array_hasil)
print(array_tambah)

print()

array1 = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
array2 = np.ones((1, 3), dtype=int)

array_hasil = array1 + array2

print(array_hasil)

[2 3 4]
[11 12 13]

[[2 3 4]
 [2 3 4]
 [2 3 4]]


### Pengurangan Array

Operasi aritmatika berikutnya yang didukung adalah operasi pengurangan. Berikut adalah contoh penggunaanya:

In [24]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.ones(3, dtype=int)

array_hasil = array1 - array2
array_kurang = array1 - 10

print(array_hasil)
print(array_kurang)

print()

array1 = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
array2 = np.ones((1, 3), dtype=int)

array_hasil = array1 - array2

print(array_hasil)

[0 1 2]
[-9 -8 -7]

[[0 1 2]
 [0 1 2]
 [0 1 2]]


### Perkalian Array

Berikutnya adalah operasi perkalian yang bisa dilihat pada contoh kode program berikut:

In [25]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.ones(3, dtype=int)

array_hasil = array1 * array2

print(array_hasil)

print()

array1 = array2 = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])

array_hasil = array1 * array2

print(array_hasil)

[1 2 3]

[[1 4 9]
 [1 4 9]
 [1 4 9]]


### Pembagian Array

Mirip seperti perkalian, berikut contoh dari operasi pembagian pada array:

In [26]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.ones(3, dtype=int)

array_hasil = array2 / array1

print(array_hasil)

print()

array1 = array2 = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])

array_hasil = array1 / array2

print(array_hasil)


[1.         0.5        0.33333333]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Dot Product

Perkalian dalam matriks ada dua jenis yaitu cross product dan dot product. Mekanisme perkalian cross product sudah terbahas dalam operasi perkalian array. Bagaimana dengan dot product? Berikut gambaran operasi dot product pada Array:

<img src = "https://arrayfire.org/docs/matrix_vector_dot_product.png" alt = "Ilustrasi Dot Product pada Matriks">

><b>Catatan:</b> Tetap perhatikan aturan perkalian pada matriks (dimensi harus memenuhi aturan MxN . NxO). Hasil dot product dari matriks berdimensi MxN . NxO adalah matriks berdimensi MxO

Numpy memiliki fungsi ``dot()`` untuk mendukung proses dot product ini. Berikut ini adalah contoh penggunaannya:

In [27]:
import numpy as np

matriks1 = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
matriks2 = np.array([[1],[2],[3]])

dot_product = np.dot(matriks1,matriks2)
print(dot_product)

[[14]
 [14]
 [14]]


### Agregat Fungsi pada Numpy

Array pada numpy bisa dikenakan operasi agregat. Tentunya hal ini sangat berguna dalam melakukan pengolahan data. Operasi agregat yang bisa dikenakan pada array numpy dapat dilihat pada tabel berikut:

| Operasi Agregat | Penjelasan |
| :--- | :--- |
| max() | Mengembalikan nilai berupa elemen terbesar di array |
| min() | Mengembalikan nilai berupa elemen terkecil di array |
| sum() | Menjumlahkan seluruh elemen pada array |
| mean() | Menghitung rata-rata elemen pada array |

Berikut contoh penggunaannya:

In [7]:
import numpy as np

array = np.array([1, 2, 3, 30, 21, 15, 110, 101, 102])

print(array.min())
print(array.max())
print(array.sum())
print(array.mean())

print()

array = np.array([[1, 2, 3], [30, 21, 15], [110, 101, 102]])

print(array.min())
print(array.max())
print(array.sum())
print(array.mean())

1
110
385
42.77777777777778

1
110
385
42.77777777777778


### Unique value di Array

Apabila kita membutuhkan array yang isinya unique dan juga membutuhkan berapa jumlah elemen unique-nya, kita bisa melakukan mekanisme berikut:

In [29]:
import numpy as np

array = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
print(array)

array_unique = np.unique(array)
print(array_unique)


[11 11 12 13 14 15 16 17 12 13 11 14 18 19 20]
[11 12 13 14 15 16 17 18 19 20]


Kita juga bisa mengetahui posisi/letak dari nilai yang menyatakan indeks pertama dari nilai unique tersebut, kita bisa menggunakan parameter ``return_index = True`` di fungsi ``unique()`` sebagai berikut:

In [30]:
import numpy as np

array = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
print(array)

array_unique, index_unique = np.unique(array, return_index = True)
print(array_unique)
print(index_unique)

[11 11 12 13 14 15 16 17 12 13 11 14 18 19 20]
[11 12 13 14 15 16 17 18 19 20]
[ 0  2  3  4  5  6  7 12 13 14]


Selain parameter ``return_index``, kita bisa menambahkan parameter ``return_counts`` untuk mendapatkan jumlah elemen unique pada array. Contohnya sebagai berikut:

In [31]:
import numpy as np

array = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
print(array)

array_unique, jml_elemen = np.unique(array, return_counts = True)
print(array_unique)
print(jml_elemen)

[11 11 12 13 14 15 16 17 12 13 11 14 18 19 20]
[11 12 13 14 15 16 17 18 19 20]
[3 2 2 2 1 1 1 1 1 1]


### Transpose Matriks

Kita bisa menggunakan fungsi ``reshape()`` pada matriks untuk membantu melakukan operasi transpose matriks. Gambaran operasi transpose pada matriks dapat dilihat pada gambar berikut:

<img src = "https://idschool.net/wp-content/uploads/2017/11/Transpose-Matriks-1-e1510690764387.png" alt = "Ilustrasi Transpose Matriks">

Berikut contoh kasusnya:

In [32]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])
print(array)

print()

array_transpose = array.reshape(3,2)
print(array_transpose)

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]


### Reverse Array

Kita bisa menggunakan fungsi ``flip()`` untuk me-reverse elemen pada array. Berikut contoh penggunaannya:

In [33]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(array)

print()

array_reverse = np.flip(array)
print(array_reverse)

[1 2 3 4 5 6 7 8]

[8 7 6 5 4 3 2 1]


In [34]:
import numpy as np

array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(array)

print()

array_reverse = np.flip(array)
print(array_reverse)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


### Flattening Matrik ke Array

Kita bisa membuat matriks (array dua dimensi) menjadi array 1 dimensi dengan menggunakan fungsi ``flatten()``. Berikut contohnya:

In [35]:
import numpy as np

matriks = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(matriks)

print()

array = matriks.flatten()
print(array)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[ 1  2  3  4  5  6  7  8  9 10 11 12]


### Hands on Lab 1: Bermain dengan kecepatan

Diberikan data jarak dan waktu tempuh sebagai berikut:

| Jarak (Km) | Waktu Tempuh (Jam) |
| :--- | :--- |
| 100 | 2.5 |
| 84 | 2.3 |
| 200 | 3.4 |
| 5 | 0.1 |

Carilah:

1. Kecepatan untuk masing-masing perjalanan
2. Kecepatan rata-rata dari seluruh perjalanan
3. Kecepatan paling cepat dan paling lambat

In [13]:
import numpy as np

jarak = np.array([100, 84, 200, 5])
waktu = np.array([2.5, 2.3, 3.4, 0.1])

kecepatan = jarak / waktu
print(kecepatan)

kecepatan_rata = kecepatan.mean()
print(kecepatan_rata)
print(kecepatan.max())
print(kecepatan.min())

[40.         36.52173913 58.82352941 50.        ]
46.336317135549876
58.82352941176471
36.52173913043479


### Hands on Lab 2: Bermain dengan nilai

Diberikan data nilai akhir dari kelas IPA 1 (100 siswa) untuk mata kuliah Biologi sebagai berikut:

``75, 70, 65, 50, 73, 58, 53, 69, 77, 62, 61, 70, 54, 66, 53, 51, 64,
52, 50, 77, 68, 63, 61, 68, 58, 67, 63, 67, 72, 70, 71, 60, 68, 75,
74, 62, 61, 76, 52, 54, 73, 72, 66, 56, 76, 60, 54, 51, 70, 70, 51,
67, 57, 67, 74, 56, 61, 54, 58, 64, 60, 54, 67, 74, 61, 72, 57, 54,
70, 55, 62, 61, 52, 60, 64, 64, 56, 79, 75, 73, 65, 64, 68, 69, 63,
76, 76, 76, 56, 51, 61, 70, 79, 55, 66, 66, 58, 53, 52, 57``

Hitung:
1. Rata-rata nilai
2. Hitung berapa kemunculan dari setiap nilai yang ada
3. Nilai terbesar dan terkecil
4. Bentuk kelompok nilai. Setiap kelompok berisi 10 nilai siswa. Hitung poin 1 sampai 3 untuk setiap kelompoknya.

# Scipy

Scipy adalah library yang memungkinkan kita melakukan perhitungan scientific, di antaranya:

1. Integration
2. Optimization
3. Interpolasi
4. Fourier Transform
5. Aljabar Linear
6. Pengolahan Data Spasial
7. Statistika
8. Multidimensional Image Processing.

Scipy bekerja sama dengan numpy (dibangun berdasarkan numpy) dalam melakukan pemrosesan perhitungan scientific ini. Bahkan module/library ini bisa membantu visualisasi data (menggunakan matplotlib). Seperti biasa, pastikan ``scipy`` sudah diinstall pada environment Python anda. Apabila belum, silakan jalankan perintah berikut:

<b>Instalasi via pip</b> <br>
``pip3 install scipy``

<b>Instalasi via conda</b> (secara default sudah tersedia ketika instalasi Anaconda atau Miniconda) <br>
``conda install scipy``

Module ``scipy`` ini membutuhkan module ``numpy`` untuk bisa dijalankan (dependencies). 

Berikut adalah bahasan contoh penggunaan module ``scipy``.

In [1]:
!pip3 show scipy

Name: scipy
Version: 1.6.2
Summary: SciPy: Scientific Library for Python
Home-page: https://www.scipy.org
Author: 
Author-email: 
License: BSD
Location: /usr/local/anaconda3/lib/python3.8/site-packages
Requires: numpy
Required-by: statsmodels, seaborn, scikit-learn, scikit-image


In [36]:
import scipy as sc

print(dir(sc))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'LowLevelCallable', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_UFUNC_API', '__SCIPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__loader__', '__name__', '__numpy_version__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_deprecated', '_distributor_init', '_fun', '_key', 

## Module Special di Scipy

Modul ini digunakan untuk operasi perhitungan beberapa kasus di matematika seperti: exponent dan trigonometri. Dokumentasi perihal entity dari module ini dapat dilihat di https://docs.scipy.org/doc/scipy/reference/special.html. Berikut beberapa contoh penggunaan module ``special``:

### Exp10 dan exp2

In [37]:
from scipy import special

hasil = special.exp10(3)
print(hasil)

hasil = special.exp2(10)
print(hasil)

1000.0
1024.0


### Fungsi Trigonometri

Mirip seperti module ``math`` di Python, module scipy melalui module special-nya menyediakan fasilitas untuk perhitungan trigonometri. Ilustrasi trigonometri untuk sudut spesial dapat dilihat pada gambar berikut:

<img src = "https://lh3.googleusercontent.com/proxy/zjsYoEJSi6jFNRewu1JUxDRE1M7QzF7XJmfEjEOxgeiG1wOVn7wx3JN7bsj4pIT_aLvc0_gg1fPW8WeSG28-NyE6-z9eI0we4QypuatFX6VaVaM5WQ3Dj8NN" alt = "Ilsutrasi tabel trigonometri sudut special">

Berikut contoh penggunaanya:

In [44]:
from scipy import special as sp

# Sudut 0
print(sp.sindg(0))
print(sp.cosdg(0))
print(sp.tandg(0))
print(sp.cotdg(0))
print()

# Sudut 30
print(sp.sindg(30))
print(sp.cosdg(30))
print(sp.tandg(30))
print(sp.cotdg(30))
print()

# Sudut 45
print(sp.sindg(45))
print(sp.cosdg(45))
print(sp.tandg(45))
print(sp.cotdg(45))
print()

# Sudut 60
print(sp.sindg(60))
print(sp.cosdg(60))
print(sp.tandg(60))
print(sp.cotdg(60))
print()

# Sudut 90
print(sp.sindg(90))
print(sp.cosdg(90))
print(sp.tandg(90))
print(sp.cotdg(90))
print()


0.0
1.0
0.0
inf

0.49999999999999994
0.8660254037844387
0.5773502691896256
1.7320508075688767

0.7071067811865476
0.7071067811865475
1.0
1.0

0.8660254037844387
0.49999999999999994
1.7320508075688767
0.5773502691896256

1.0
-0.0
inf
0.0



## Module Integrate
Module ``integrate`` di ``scipy`` bisa membantu kita dalam menghitung fungsi integral baik integral lipat satu, lipat dua, maupun lipat tiga. Sebagai contoh kita mau menghitung fungsi integral berikut:

![Integral Terbatas](https://drive.google.com/uc?export=view&id=1e97DeDhkma_Kz0yCWa3sNBoS-fBbIZa3)

Misal f(x) = x<sup>2</sup>, berikut contoh programnya:

In [46]:
from scipy import integrate as itg

fungsi = lambda x: x**2
print(itg.quad(fungsi,0,10))

(333.33333333333326, 3.700743415417188e-12)


## Module linalg

Module ``linalg`` digunakan untuk menyelesaikan permasalahan pada domain Aljabar Linear. Salah satu kasus yang sering ditangani adalah operasi invers matriks. Dokumentasi perihal invers matriks dapat dilihat di https://www.ruangguru.com/blog/cara-mencari-determinan-dan-invers-matriks. Berikut adalah contoh penggunaan module ``linalg`` untuk perhitungan invers matriks dan determinannya:

In [50]:
from scipy import linalg as lg
import numpy as np

matriks = np.array([[1, 2], [3, 4]])
print(matriks)

print()

invers_matriks = lg.inv(matriks)
print(invers_matriks)
print(lg.det(matriks))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0


## K-Means Clustering di Scipy

Salah satu kelebihan module ``scipy`` adalah module ini mendukung proses Data Mining Clustering. Apakah sudah memahami Data Mining Clustering? Apabila belum, silakan pelajari secara singkat perihal Data Mining Clustering di slide berikut: https://www.slideshare.net/adfbipotter/data-mining-clustering. Algoritma yang didukung oleh ``scipy`` adalah algoritma k-Means. Berikut adalah contoh penggunaan k-Means menggunakan ``scipy``:

<b>PROSES 1</b>  - Ubah data menjadi array

In [82]:
from numpy import array
from scipy.cluster.vq import kmeans2
import matplotlib.pyplot as plt

# Buat array dari data
data_tinggi_berat = array([[179., 79.],
                           [170., 70.],
                           [175., 79.],
                           [178., 78.],
                           [175., 77.],
                           [175., 75.],
                           [180., 80.],
                           [182., 80.],
                           [179., 89.],
                           [178., 78.]])


<b>PROSES 2</b> - Tentukan berapa cluster yang mau dibentuk dan tentukan centroid-nya. Dalam kasus ini kita akan pakai 3 cluster dan centroid acak

In [65]:
centroid, label = kmeans2(data_tinggi_berat, 3, minit='points')

print(centroid)

[[180.33333333  83.        ]
 [176.66666667  77.66666667]
 [170.          70.        ]]


<b>PROSES 3</b> - Dapatkan hasil cluster dan cari karakteristiknya

In [81]:
cluster1 = data_tinggi_berat[label == 0]
cluster2 = data_tinggi_berat[label == 1]
cluster3 = data_tinggi_berat[label == 2]

print('Cluster 1:')
print(cluster1)
print()
print('Cluster 2:')
print(cluster2)
print()
print('Cluster 3:')
print(cluster3)
print()

print('Karakteristik Cluster 1')
print("Max:",data_tinggi_berat[label == 0].max(axis = 0))
print("Min:",data_tinggi_berat[label == 0].min(axis = 0))
print("Mean:",data_tinggi_berat[label == 0].mean(axis = 0))
print()

print('Karakteristik Cluster 2')
print("Max:",data_tinggi_berat[label == 1].max(axis=0))
print("Min:",data_tinggi_berat[label == 1].min(axis=0))
print("Mean:",data_tinggi_berat[label == 1].mean(axis=0))
print()

print('Karakteristik Cluster 3')
print("Max:",data_tinggi_berat[label == 2].max(axis=0))
print("Min:",data_tinggi_berat[label == 2].min(axis=0))
print("Min:",data_tinggi_berat[label == 2].mean(axis=0))
print()


Cluster 1:
[[180.  80.]
 [182.  80.]
 [179.  89.]]

Cluster 2:
[[179.  79.]
 [175.  79.]
 [178.  78.]
 [175.  77.]
 [175.  75.]
 [178.  78.]]

Cluster 3:
[[170.  70.]]

Karakteristik Cluster 1
Max: [182.  89.]
Min: [179.  80.]
Mean: [180.33333333  83.        ]

Karakteristik Cluster 2
Max: [179.  79.]
Min: [175.  75.]
Mean: [176.66666667  77.66666667]

Karakteristik Cluster 3
Max: [170.  70.]
Min: [170.  70.]
Min: [170.  70.]



<b>PROSES 4</b> - Visualisasikan Cluster

In [ ]:
plt.plot(cluster1[:, 0], cluster1[:, 1], 'o', alpha=0.5, label='cluster 1')
plt.plot(cluster2[:, 0], cluster2[:, 1], 'd', alpha=0.5, label='cluster 2')
plt.plot(cluster3[:, 0], cluster3[:, 1], 's', alpha=0.5, label='cluster 3')
plt.plot(centroid[:, 0], centroid[:, 1], 'k*', label='centroids')
plt.axis('equal')
plt.legend(shadow=True)
plt.show()
